Ndahechái moõpa ojehechauka pe flecha hovyũ.
Kuña ojehechahína ta'ãngamýipe oñeno aja
Peteî poapy ohechaukáva peteî hotdog kesu, salsa picada ha ketchup reheve.
Peteî tape ojehechaukáva heta hendápe
Heta tapicha oĩ peteĩ y rembe'ýpe surf tabla reheve ha mokõi kuimba'e ohechauka y gotyo.
Peteî kuimba'e ojoguáva ha ijajúra reheve ohechauka ipo oñe'ê jave
MBO'EHA YVYRY REMI OÑE'ÊVA OÑE'ÊVA OÑE'ÊVA OÑE'ÊVA OÑE'ÊVA OÑE'ÊVA OÑE'ÊVA OÑE'ÊVA OÑE'ÊVA OÑE'ÊVA
Peteî tapicha oipyhyva'ekue peteî control remoto ohechaukáva peteî televisión.
Peteĩ surfista ohecha peteĩ ola oitypáva y rembe'ýpe.
Peteĩ po ohechauka peteĩ ta'ãnga'i morotĩ ha hũ peteĩ pantalla tuichávare.
Kuña ohechaukáva yvága gotyo oñe'ẽ jave peteĩ kuimba'e ndive.
Peteî kuimba'e ohechaukáva ambue gotyo, ha'eño.
Peteî kuimba'e opresenta ta'anga ha ohechauka peteĩ logo iku'arandúpe.
Kuña omoporãva'erã pe yvyra omokã hag̃ua iñakã ha'ete peteĩ arma.
Peteî karia'y oñembo'y ha ohechauka ta'angápe.
Kuña omotenondéva Wii remoto cámara gotyo
Peteî kuimba'e ohechaukáva peteî mitâ'i py.
Kuña ohechauka peteĩ teléfono peteĩ cubierta-pe.
peteĩ cámara oapuntáva cámara ha micrófono peteĩ altavoz-pe.
Ñe'ẽpapára katupyry ohóva escenario-pe ohechauka iñirũrãme
mokõi tapicha omohendava'ekue peteĩ mesa tembi'u
Heta tapicha omohenda paraguasúpe yguasu ypýpe.
Peteî mesa oñembosako'íva pizza-gui.
Oñemohenda peteĩ mesa vino ryru ha peteĩ tarta reheve.
Oĩ mokõi tembi'u ha peteĩ yva oñemboja'o mesa ári.
Peteî kuimba'e skateboard ári oîva peteî cámara renondépe.
Peteĩ cámara oñemoĩva peteĩ mbarakaja okeha renondépe.
Peteĩ ñemenda oñemohendava peteĩva umi paraguái ojeitypárõ
Mokõi apyka oñemohenda yguasu rembe'ýpe.
Mesa de comedor oñemoĩva opáichagua yva, tarta ha pan reheve.
Peteĩ mesa mesa mesa-pe oñembosako'i peteĩ karu guasu.
Peteî mesa puku oñemoîva heta yva, verdura ha tembi'u apo reheve.
Peteî tapicha oveve yvágare peteĩ skateboard ári kuarahy oike jave.
Heta mba'yru guasu oñemoĩ umi kuimbe guasu ykére.
Trine de juguete oñemohenda ha ojefotografa.
Peteĩ kuimba'e ohechauka kuñáme peteĩ tarta de cumpleaños tuicháva.
Peteĩ kavaju ojehechauka peteĩ aty'i tapichápe.
Peteĩ kuimba'e ohechauka peteĩ kavaju hũ peteĩ aty tapichápe.
Kuña ohechauka ikamby kamera-pe.
Tapichakuéra aty ohechaukava'ekue iñirũrã celular-kuérape peteĩ atyguasu apyka guasúpe.
Collage peteĩ tienda telefónica-pegua kuña ohechaukahápe hete rasgo.
Kuñáme ojehechauka mba'éichapa oñembosarái disco golf-pe óga ryepýpe
Peteî kuimba'e ohechauka mitâ'i mitâ'ípe mba'éichapa oguata peteî tabla de padel.
Peteĩ TV ohechaukáva mokõi kuimba'e sapatu ha kuña rehe.
Irundy ta'anga peteî koty ohechaukáva tupa, ta'anga ha peteî computadora portátil mesa ári.
Kuña ohechauka kuimba'épe peteĩ víno ryru.
Kuña porã porã, ao hovyũva, ohupi ijao ojechauka hag̃ua iñakã.
Peteî tapicha guante reheve ohechauka aravo aravo ipópe
Peteĩ kuimba'e ha kuña ohechaukava'ekue hembi'u.
Mokõi kuimba'e ijyvatevéva oñopytyvõ oñondive.
Peteĩ kuimba'e ha peteĩ kuña oñopytyvõ peteĩ tarhéta ypýpe.
Oĩ angirũ oñopytyvõva estadio de béisbol-pe.
Peteî kuimba'e motocicleta ári ohasa ambue mba'yrumýi rehe.
Takuare'ẽ morotĩ ha pytã, ohasa peteĩ táva mbytépe.
Peteĩ tren pytã peteĩ rrikétepe ohasa ohóvo peteĩ óga yvate.
Peteĩ mbarakaja ohasa peteĩ ciclista ha peteĩ motociclista ykére.
Y ohasa peteĩ puente guýpe ha umi mba'yrumýi ohasa ijyvatevehápe.
Peteĩ esquiador ohasa mokõi tapicha peteĩ snowmobile ári.
Peteĩ tren orekóva motor de vapor ohasa peteĩ estación ferroviaria rupi.
peteĩ tapicha itujavéva ome'ẽva tembi'u mitãrusukuérape
mba'yrumýi ohóva tape rupi ohasa tesape'a
Peteî mba'yrumýi pya'e ohasa peteĩ tape henyhêva mba'epu'apu'a.
Peteĩ tren pytã ohasa hína y ári peteĩ puévlo ári.
Tapichakuéra opyta okañy yvýre peteĩ baño-pe, orekóva urinal ha toaleta.
Heta tapicha motocicleta ári ohasa óga ypýpe.
Peteî tapicha ohasáva peteî frisbee ipy'a mbytépe.
Peteî mitâ'i ojupi kosina kuápe.
Mitâkuña'i oipyso ipo peteî torta pehênguére.
Peteĩ jagua ojupi yvytúpe ojagarra hag̃ua peteĩ frisbee ovevéva.
Oî po osêva ao'iha guive ha ohóva peteî kuña okehápe.
Mokõi karia'y ojagarra peteĩ disco.
Mitãkaria'y ojagarra peteĩ manzana pytã.
Kuña ojupiva'ekue ombopu hag̃ua peteĩ balón de tenis peteĩ raqueta reheve.
Peteî kuimba'e oipyso ipo ome'ê haĝua peteî mba'e elefante-pe.
Peteĩ elefante ra'y oñakãity peteĩ vosa hovy rehe peteĩ zoológico-pe.
Tapichakuéra oike peteĩ ka'avo parral yvotytýpe ha ombyaty ka'avo parral.
Peteî po plástico oipysóva peteî blender plástico joguaha.
Peteî kuimba'e oipysóva ipópe peteî plato peteî pizza pehê.
Peteĩ tapicha oipyso ipo ojagarra hag̃ua peteĩ vakapipopo.
peteĩ tapicha oipyhýva control remoto
Peteĩ tenista oipyso ikorasõ oity hag̃ua peteĩ pelota de tenis
Kuñataĩ oñakãrapu'ã oheka hag̃ua pe pelota de tenis raqueta reheve.
Kuña oike pe pan apoha pe tatakuápe
peteĩ kuimba'e oguejy oheka peteĩ mba'e peteĩ caja-pe
Peteĩ elefante oipyso ijati'y ojupi hag̃ua pe barrera ári.
Peteî kuimba'e oipyso peteî raqueta omoingévo peteî pelota de tenis.
Peteĩ mitã'i oipyso ipo peteĩ frisbee naranja-guápe.
Kuña hakã pytã ombotýva ipo tenis bola ha raqueta rehe.
Peteî kuimba'e peteĩ escalera ári oñeha'âvo oguahê aranduka
kuña oipyso ijyva oity mboyve peteĩ pelota de tenis
Kuña ojupi yvytúre peteĩ rakíllo reheve oity hag̃ua peteĩ balón oúvape
Kavaju ojupi peteĩ korapýpe ha ho'u ka'avo.
heta vakapipopo ñembosarái oha'ã peteĩ ñembosarái
Peteĩ tapicha oha'ã hína peteĩ partido de tenis-pe.
Peteî kuimba'e oityvyro violín ikuñáme
Mokõi mitã'i oñopehẽngue peteĩ vakapipopo rehe.
mokõi kuña ha irundy kuimba'e oñopehẽngue peteĩ frisbee morotĩ rehe
Heta kuimba'e oñembosarái hína peteĩ ñúme, oĩhápe yvyramáta, muro, autobús ha heta óga ypytũ.
Peteî kuimba'e opytu'u peteî banco yvyrágui ojejapóva.
Peteĩ jagua omopytu'u iñakã ijára akãme
Mokõive oñani opytu'u aja banco-kuérape pe muelle-pe, táva rovái
Mokõi mitã oñemoĩ iñakã rehe ipo ári.
Kuimba'e opytu'úva ára pukukue rire ipy yvatevehápe iñemohendahápe.
Kuña omopyenda iñakã ijyva akatúa ári.
Peteĩ esquiador opytu'u hína peteĩ carrera mbytépe.
Peteĩ cerveza opytu'úva peteĩ motocicleta ári.
Peteî tapicha opyrûva ha opytu'úva peteî apyka ári peteî mbarakaja hũ ykére.
Tapichakuéra oguata ohóvo ha'eteva'ekue peteĩ centro comercial heta tienda reheve.
Mokõi tapicha oguatáva tape mboypýri oguerahahápe paraguasokuéra.
Mokõi kuña oguatáva peteĩ tape rupi peteĩ paraguasú rosa guýpe.
Peteî kuimba'e ojupi skateboard-pe oguata jave iky'a rehe.
Mokõi tapicha oguata corredor rupi ha peteĩ kuimba'e katu ho'u peteĩ oso de peluche guasu ykére.
Mokõi tapicha oguata y rembe'ýpe paraguasukuéra reheve.
Peteĩ karia'y oguata ohóvo y apére peteĩ tabla de surf reheve.
Mymba sa'yju oguatahápe peteĩ aty tapicha ndive.
Peteî tapicha oguatáva tape yképe peteî tape henyhêva gente pyharekue.
Mokõi tapicha oguata hína jaguaretépe pe nieve ári.
Mokõi kuimba'e ohasa peteĩ mbusúpe.
Peteĩ kuimbaʼe ohasa ohóvo peteĩ tren ykére peteĩ estación de trénpe.
Kuña omoîmbaite tomate peteî pizza-pe.
Mitãkuña'i omoĩ peteĩ sapatu pytã iñarandu'ỹva ikóga akãre.
Kuña omondeva'ekue ijao oma'ẽ aja aravo rehe
Peteĩ kuñakarai chef omoĩ tembiʼu peteĩ plato ári.
Ko kuimba'e omoî monéda peteî medidor-pe
Peteî tapicha omoîva'ekue tembi'u rykue peteî tatakuápe peteî espátula rupive.
Peteĩ mitãrusu omoĩ umi ingrediénte peteĩ blender-pe.
Kuimba'e omohenda yvyramátape arete jave.
Peteî kuimba'e omoîva tembi'u peteî karrétape cocina-pe.
Tapichakuéra omoĩva tataindy peteĩ tarhéta ári.
Oĩ peteĩ kuimba'e omondeva'ekue ijajúra.
Peteî kuimba'e oikóva omoîtaha iky'a ryru peteî tatakuápe.
Peteĩ esquípe oñani peteĩ óga ypýpe.
Peteî kuimba'e omoîva peteî kuimbe'i peteî microondas-pe.
Peteî kuimba'e omoîva peteî pizza peteî tatakuápe.
peteî kuimba'e omoîva kure ka'avo roguépe
Kuña omoîva hi'upyrâ peteî tarta ojejapóva hógape.
Kuña omohendáva pimiénto ipire pizza-pe peteĩ restaurante-pe.
Peteĩ karrétape, peteĩ portátil omoĩ hína umi mbaʼe orekóva peteĩ trénpe.
Peteĩ kuimba'e omoĩ tembi'u iplatápe ha peteĩ kuña omosarambi vino.
Peteî kuimba'e koty ryepýpe omohendahína peteî mbayru morotî.
Kuña pyahu snowboard-pe omonde guante.
Peteî kuimba'e ojupiva'ekue peteî apyka guasu pytâ ári peteî kavaju japu ári.
Peteĩ mbarakaja hũ ojupi peteĩ bañera-pe.
Peteî kuimba'e ojupi peteî tápia de stop-pe.
Mitãkuña osẽva peteĩ vosa'ígui yvýpe
Mitãkuña ojupi umi jeráfa gotyo ha ha'ekuéra oipyso ijyva heseve.
Mitãkaria'y ojupi peteĩ frigorífico ryepýpe.
Mokõi tapicha ojupíva yvyty ijyvyra rehe
Tapichakuéra ojupi yvyty ijyvytu rehe esquí-pe
Peteĩ kuimba'e ojupi peteĩ elefántere peteĩ apyka ári.
Peteî kuimba'e ojupi peteî silope itráko henyhẽgui.
Peteî jagua ojupi peteî tapicha ári okeva'ekue peteî sóvape.
Peteî jagua oñehetû chupe peteî kuimba'e.
Peteî mbarakaja ojepohéiva'ekue.
Mitâra'y iñakârague omopyrû peteî kakuaáva.
Kuña oñeha'ã omopotĩ hag̃ua ijuru peteĩ kuãirũ tuichaitéva reheve peteĩ ñemuha guasúpe.
Peteî pelotéro ombopu peteî pelota.
Peteĩ tenda oñemopu'ãva'ekue nieve-pe yvyramáta ha esquí ypýpe.
Peteĩ pelotero oñani ojagarra hag̃ua peteĩ pelóta ojeity vaʼekue
Kuña ojupiva'ekue ombopu hag̃ua peteĩ softbol.
Peteî kuimba'e iñakâ morotîva tatuado ogueraha ijyvyrakuera y rembe'ýpe.
Mbohapy kuimba'e ogueraháva heta valija peteĩ tape yképe
Kakuaáva ogueraháva mitãme equipo completo-pe, oikehápe esquí pindo pindo ári.
Peteĩ jagua hũ oñani peteĩ ñu hũ ári.
Kuimba'e ha kuñataĩ oñani hína yvyku'i ári.
Peteĩ tenista oñani ikatu hag̃uáicha oity pe pelota.
Peteî aty militar-kuéra oguata ohóvo peteî autobús escolar gotyo.
Peteĩ tape ojejapóva cemento-gui oguata paralelo umi vía ferroviaria rehe.
Mokõi tapicha oñani peteĩ vakapipopo rapykuéri peteĩ ñu ñu'ãme.
Kuña oñani hína peteĩ tape karape ári ha peteĩ jagua katu peteĩ skate ári.
Heta kuimba'e ha kuña vakapipopo ao rehe oñani peteĩ campo henyhẽva tapicha rehe ha opyta tapykuépe.
peteĩ surfista oñani umi ola-pe peteĩ y rembe'ýpe ikurusu reheve
Tapichakuéra oguerekóva equipaje ojere ha opukavy.
Peteĩ autobús ojere ijykére peteĩ accidente vaiete.
Peteĩ mba'yruguata guasu hovyũva ojere peteĩ tape tavaguasúpe.
Peteĩ táxi ojere ykére peteĩ tape henyhẽva mba'epu.
Peteĩ mbusy hovy ha hovyũ oúva peteĩ tape tavaguasúgui.
Kuña pyahu iporâitereíva omyendy y tujápe.
Peteĩ ta'angambyry oñembo'ýva peteĩ apyka yvyrágui.
Peteĩ kamiõ oñemongora peteĩ tape kurusu rehe.
Peteî kuimba'e omyendy peteî hidrante peteî yvyty itaguigua ypýpe.
Kuimba'e ojere ijehe ha omaña pe espejo-pe.
Peteĩ mano ojereva peteĩ blender morotĩ rehe.
Peteî karai kamisa hũva oipe'a peteî tatarendy rokê ha omaña tatarendy ryepýpe.
Nde, kuimba'e, upéva oipe'a hína vino ryru.
Kuña oipe'áva computadora portátil regádo koty guasúpe
Peteî tapicha oipe'áva peteî pizza caja peteî kotýpe.
Peteĩ elefánte oipeʼa ijuru mokõi kuimbaʼe omaña aja.
Peteĩ cocina michĩva ojepe'áva ambue kotýpe.
Peteî kuimba'e oipe'áva peteî hidrante omosêva y ro'ysâ peteî tape rehe.
Peteî kuimba'e ohai peteî selfie oipe'ávo computadora pyahu.
Yva'a'i mbovymi peteĩ ysyryguasu henyhẽva yga'ígui.
Peteĩ isla peteĩ tienda de comestibles-pe henyhẽva heta verdurágui.
Pe mesa henyhẽ tembi'u parralla-gui
Kuña omyenyhẽ champán-gui umi kuãirũ.
Pe mbo'ehao koty henyhẽ umi temimbo'e kirirĩháre.
Mitãkuña'i peteĩ hidrante-pe omyanyhẽvo burbuja.
Peteĩ kuimbaʼe omyendy umi kandela peteĩ kuñataĩ oguerekóva ipópe.
Peteĩ pelotero ombopupu peteĩ burbuja chicle.
Kuña oguapýva, iñakãrague yvytu reheve.
Peteĩ locomotora michĩva omyanyhẽva peteĩ arapytu.
peteĩ kuimba'e ohypýi peteĩ bola plástica-pe
Peteî jagua omokôva peteî kuimba'e.
Peteĩ jockey ogueraha ikavaju ha umi fotógrafo katu ohai ta'anga.
Peteĩ mymba aty ojegueraha peteĩ hendápe tape mboypýri.
Peteî policía omotenonde tape ambue tapicha oguatáva motocicleta-pe.
Peteĩ guardia de color oguerekóva bandera omyakãva peteĩ desfile peteĩ tape pukukue.
Peteĩ kavaju ojegueraha mombyry ikangýgui
Heta tapicha oñembo'y ha oma'ẽ guyra kavaju ári ogueraháva heta kavaju hapykuéri
Heta tapicha oguapy mesa jerére peteĩ koty'i'i oguerekóva peteĩ computadora, aranduka ha kuatia.
peteî kuimba'e desierto-pe oguapýva motocicleta ári
Peteĩ kanóa oĩ yguasu ári.
Peteĩ aty aviõ michĩva oguapýva peteĩ asfalto ári.
Peteĩ tren oguapýva umi vía-pe peteĩ plataforma ykére.
Peteî kuimba'e kamisa hovy morotîva oguapýva peteî vosa'i ári.
Peteî pizza oguapýva salada ykére.
Heta mitã oguapy peteĩ vy'aguasúpe
Peteî kuimba'e ombojeguaka microondas ári ojepyso aja peteî apyka ári.
peteî kuimba'e ojejopy peteî raqueta de tenis ipópe
Mitã'i oñembo'y peteĩ kosináme pe frigorífico okẽ ojepe'a ha mitã'i oñembo'y pe frigorífico rehe iñakãnguére.
peteĩ sombrilla oñembotýva ojejopýva peteĩ óga korapýpe
Kuñataĩ iñakãre oñakãityva'ekue, ojepyso peteĩ mesa ári peteĩ pizza rectangular ári, peteĩ calendario ha contenedor oĩva parére.
Peteî kuimba'e oñesû peteî mesa ári peteî koty hotel-pe.
Peteî kuimba'e ojepyso ha oñembosako'i ho'a hag̃ua pe ñembosarái aja.
Peteĩ traváho hetaitereíva pe esklávorupi, ha pe signálo de stop katu ojerepa.
Kuimba'e ojoguáva ao ha ojopýva tataindy peteĩ tarógape.
Peteĩ señál de parada ojejoko peteĩ intersección-pe.
Mitâ'i oñemboja peteî korapýpe ohecha haĝua heta ovecha ra'y.
Kuñataĩ ijao morotĩva oñesũ peteĩ vaka ári ha oreko peteĩ sapatu de paja.
Peteĩ jirafa ojepyso peteĩ parére peteĩ zoológico-pe.
peteĩ kuña ojejopy peteĩ ykua ári omopotĩvo ijyva peteĩ kesu elektrisado reheve
Peteĩ póstere katuete oñesũ yvy gotyo.
Peteĩ mba'yrumýi motenondehára peteĩ pista-pe ojere peteĩ curva-pe.
Peteĩ kamiõ ohasa peteĩ tren rapére.
Umi pytagua ohasa peteĩ tape ykére peteĩ táva henyhẽva tapicha rehe.
Mokõi mba'yrumýi ha peteĩ mba'yrumýipe peteĩ tape ohasahápe peteĩ elefante aty.
Peteî kuimba'e omaña'ÿva peteî tovevúi ijuru ryepýpe rehe.
Kuimba'e ombojeguáva yga'i ysyryguasu rehe, yvy ijyvyteéva.
Kuña ojupi yguasu ári ha oñani.
Mokõi pirajokuaihára ombotyryry isambyhy y pytu'úpe.
Mokõive surfista oho yguasupe.
Peteî tapicha oguapýva mesa ári ha ohaiva'ekue peteî kuatia'atâ ári.
Kuña hyeguasúva ohaiva'ekue ikurape ha oguereko peteĩ oso peludo hovy.
Peteî kuimba'e ohaiva'ekue peteî mba'e oiporúrô peteî celular.
Pe hidrante tata rendy oĩva tape yképe ojepinta hovy ha morotĩ.
Oĩ avei vaka ojepintava'ekue rosa ha morotĩ rehe.
Peteĩ aravo'i peteĩ ogaguasu ári, tapichakuéra ojehai ijerére.
Peteĩ hidrante ojepinta peteĩ bandera estadounidense-icha
Tembipuru'i oĩha peteĩ cocina mbytépe ojepinta jave
Peteî kuimba'e ojupi y rembe'ýpe kuarahy resêpe
Tapichakuéra ojupi peteĩ mba'yrumýi mokõiha rendaguépe, oĩva peteĩ tape henyhẽva mba'epu'águi.
Peteĩ autobús ohaʼarõ peteĩ persóna ojupi hag̃ua hese.
Peteî kuimba'e ijao hũva ojupi yvatevehápe
Mitâkuña'i ojupi mba'yrumýipe ohóvo mbo'ehaópe.
Peteĩ kuimba'e ojupi yguasu rembe'ýpe umi ola guasu yguasu ári
Heta mitã'i ojupi skateboard-pe peteĩ puente ojepintava'ekue graffiti rupive
Kuña pyahu omokõva mba'e ryakuã peteĩ tatakuápe.
Mitã'i ombojeguáva tembi'u.
Ko mba'e ojehecha peteĩ tesa ha peteĩ juru ojopýva ko hidrante-pe.
Peteî luz de tránsito oguerekóva ta'anga oñemoha'ãngava'ekue opaite umi luz ári.
Peteĩ mba'yru yvyrágui ojejapóva plátare, oĩhápe peteĩ tapicha hova.
Mitãkuimba'e ha mitãkuña'i peteĩ mesa ári, omoha'angava'ekue ta'anga hovyũva.
peteĩ kuimba'e omomýi peteĩ frigorífico peteĩ ógape
Peteĩ kuimbaʼe oipuru peteĩ karréta omomýi hag̃ua peteĩ horno.
Peteĩ tren plata-guigua ohasa peteĩ távape
Ocho movedor oipytyvõva peteĩ tapicha ova hag̃ua hogarã pyahúpe
Umi camión de bombero oguata tape tavaguasúpe, umi mitãnguéra katu oñembosarái ijykére.
Peteĩ tren modelo tuja oguatáva umi vía ári.
Mbohapy esquiador ojupi peteĩ yvyty ári, mokõi oguejy yvyty ári ha peteĩ ojupi yvyty ári.
Mokõi kuimbaʼe ogueraha peteĩ kamión pytãʼípe yvyra
Peteĩ fritería ogueraháva donuts fritería-pe.
Umi hénte oho ha oñembyaty peteĩ lugárpe, oĩva pe óga guasu morotĩ ykére.
Peteĩ tenista oho ha'eño ha ojagarra mokõivéva ipo raqueta rehe.
Peteĩ kuimba'e oityva'ekue peteĩ vakapipopo tenis-pe.
Peteî tapicha oguata hína skateboard-pe ha oity peteî cono morotî.
Peteî mitâ'i oipurúva peteî guante de receptor oñeguenohê jave chupe peteî pelota.
Peteî kuimba'e oity peteî mba'e ha upéva opupu peteĩ bate rupive.
Mokõi kuimba'e ao ao reheve ombopu peteĩ gongue martillo reheve.
Peteĩ karréta ogueraháva heta tapicha, ojeity mokõi kavaju rehe.
Peteî kuimba'e ogueraháva apyka'i aeropuerto-pe
Ojehecha peteĩ tren de pasajeros oñembojaha peteĩ plataforma-pe.
Peteĩ autobús pytã oñepyrũ opyta peteĩ esquina-pe.
Kuña oipyhy tembi'u oje'u'ypyva'ekue tatakuágui.
Peteĩ kanóa pytã og̃uahẽ peteĩ y rembeʼýpe.
Peteĩ tren hovy ha sa'yju og̃uahẽ peteĩ estación-pe.
Peteĩ kanóa ogueraháva peteĩ yguasu rembe'ýpe peteĩ yguasu ári.
Pe mba'yruguata tavaguasu pegua opyta tape yképe.
Peteĩ kanóa motor rehegua oheja peteĩ tape ohapykuehóvo mokõi yguatápe.
Peteĩ tren og̃uahẽ pe estación de trénpe.
Peteĩ tren ohasa peteĩ óga yvate ha peteĩ tape ykére.
Peteî kuimba'e oipe'áva peteî pizza peteî tatakuágui.
Peteî kuimba'e omoñe'ê aranduka ha ambue katu ojapyhy peteî jagua.
kuña oguapýva peteĩ sombríllo guýpe omoñe'ẽ aja aranduka
Peteĩ karai omoñe'ẽva peteĩ aranduka peteĩ mitãmíme.
Mitâ'i oñeno hupápe omoñe'êvo iñermáno'i'ipe.
Kuña omohenda aravo'i heta tapicha oma'ẽ aja.
Umi ojepy'apýva peteĩ zoológico-pe oma'ẽ peteĩ elefante africano rehe.
Peteĩ aty de surfista oñatende pe y rembeʼýre.
Tapichakuéra omaña ambue kuérape tenis-pe.
Tapichakuéra omaña aviõre peteĩ korapy kupégui.
Peteî kuimba'e oguapy aviõme omaña TV.
peteĩ hotdog oñembyaty peteĩ papel de papel-pe
Kuña pyahu ojejokua peteî toalla de playa rayada hovyũva
Kuña oñapytĩva ao ao'ári oñeno rire omopotĩ hag̃ua iñakã
Peteĩ karreta joguarã oñembotýva plástico-pe henyhẽva mymba ñembosarái ha ambue mba'e rehe.
Peteî po oguerekóva peteî hotdog ketchup, mostaza ha cebola reheve ojejapiva'ekue papel de aluminio rehe.
Peteĩ kuñakarai tujami ojaho'íva peteĩ ao'i ha ho'úva tembi'u
Mitã'i ojejokua peteî toallape peteî tupa ári.
Peteĩ tapicha ombojuruja peteĩ teĩ ao pytã rehe.
Peteĩ motociclista ojere peteĩ esquina-pe iñirũ ojere aja motocicleta-gui.
Peteĩ ñemuhápe oĩ heta pláta yvyguy oñehendu'ỹva.
Ta'anga aty familia rehegua ombojeguáva tatakua ári.
Oĩ heta mbyjajere hovyũva ojejoko peteĩ óga tuja renondépe.
Kuñakarai ojopýva jeep marrón-pe
Peteî kuimba'e peteî campo-pe ombyai peteî bate de béisbol.
Ta'ãnga yma guare peteĩ kamiõ oñembyai'ypyva'ekue tape yképe.
Mitãrusu ombotyryry peteĩ toaleta peteĩ martillo michĩ reheve.
peteĩ tesapeha tape rehegua oñemboja'óva mbytépe peteĩ tekove ka'aguy ári
Peteî tapicha oîva'ekue yvytúpe ho'ávo peteî tabla de surf-gui peteî ola guasúpe.
Peteĩ jugador de fútbol ho'áva yvýpe ambue ho'ávo hese.
Kuña oñeno okehápe kuimba'e ykére, mokõivéva oguapy.
Kuimba'e ho'áva ype pe ola omombo aja chupe ijyvyrágui
Peteî tapicha oguatáva peteĩ skateboard-pe ambue ho'ávo skateboard-gui.
Peteî tapicha ojapóva truka peteĩ skateboard ári ho'a haguãicha
Peteî tapicha snowboard-pe ho'a yvate
Peteĩ kuimbaʼe hoʼa oñehaʼãvo ojagarra peteĩ ola
Peteî tapicha oipurúva esquí ho'áva peteî pindo hi'yva'ekue ári.
Peteî kuimba'e ho'a ha ikape oveve ohóvo snowboard-pe.
Mokõi kuimba'e skiádo hína ha peteĩva ho'a.
Peteĩ aty mba'yruguata oguata peteĩ tape rehe.
Heta tapicha oñembo'y tape mbytépe, oĩháme motocicleta.
Oĩ mitãnguéra Escuela Católica-pegua oñemboja'óva peteĩ fila-pe micrófono renondépe.
Heta mba'yrumýi oñemboja'óva ojoykére.
Umi mba'yrumýi oñemboja'o umi medidor de moneda-pe peteĩ tape henyhẽva tránsito-gui
Umi mba'yrumýi oñemboja'óva tape rehe tráfico-pe
Tapichakuéra oñemboja peteĩ línea-pe ojupi hag̃ua peteĩ autobús-pe peteĩ ára kuarahy'ã porãme.
Heta motocicleta oñemboja'o ojehechauka haguã.
Kuña pyahu omopu'ãva'ekue peteĩ ñana pyahu yvytúpe.
Peteĩ kuimba'e ijao'ỹre oguerekóva ipópe peteĩ kuãirũ po'i morotĩ.
Peteî kuimba'e oñembo'y hesa kangy rehe ha omboty ipópe Wii remoto.
Mokõi kuimba'e ojoko Wii control remoto.
Mitãkaria'y oguapýva yvýpe ha oguerekóva ipópe paraguasu.
Peteĩ kuñataĩ hũva, ijao morotĩva, omopu'ã peteĩ kuãirũ.
Mitâ'i hovy rehe ojagarra imemby karia'y.
Peteî kuimba'e oguapýva peteî sombrero guýpe peteî TV oîva peteî parére.
Peteî óga itaguigua itujaitereíva, oguerekóva peteî aravo'i ijyképe.
Karai omo'ãvo casco omoîva'ekue i-motocicleta oñangarekóva porã
Peteĩ reloj tuichaitereíva oñemoĩva peteĩ óga yképe.
Peteî ta'angambyry ijyvate'ỹva oñemoĩ escalera yképe.
Peteĩ kuimba'e ijao'i ha peteĩ kavaju ári peteĩ sapatu hũ.
Heta tapicha omaña peteĩ tenista rehe ombohasa jave peteĩ balón.
Peteĩ mesa mokõi tarta ha copa de champaña ha mokõi kuña ome'ẽva tarta.
Mokõi tapicha uniforme-pe omog̃uahẽ tembi'u umi hógaguápe.
Hot dog ha patatas fritas oñembojy peteĩ cartón-pe oguerekóva peteĩ mba'yrumýi forma.
Kuña peteĩ tenis korto-pe ohasávo.
Peteî pizza ñana reheve oñembohérava plato-pe
Mbohapy mba'apohára peteĩ cocina comercial-pe, omog̃uahẽ tarta.
Kuñanguéra omog̃uahẽva tembi'u café-pe.
peteĩ aty tapicha oñeme'ẽva hotdog ha patatas fritas.
Peteĩ kamiõ tembi'u ome'ẽva calamario oñemoĩva ambue kamiõ tembi'u apytépe.
Peteî tapicha omyendy peteî tataindy oîva peteî tarta pehêngue ári.
Peteĩ torre de reloj tuichaitereíva oĩ peteĩ y rembe'ýpe.
Peteî kuimba'e ao hovy reheve, ohesapéva peteî sigarríllo.
Mokõi tapicha surfín-pe, peteĩva oguata peteĩ ola-pe ambue gotyo.
Peteĩ surfista oguata peteĩ ola guasúpe yguasu ári.
Peteî kuimba'e oguata kavaju ári peteî ka'aguy'ípe.
Mokôi tapicha oguata peteî bicicleta hûre
Kuña oguata bicicleta-pe oiporuhápe teléfono inteligente.
Peteĩ kuimbaʼe oguata ohóvo y apére peteĩ tabla de surf ári
Tapichakuéra orekóva kavaju ári oguata peteĩ elefante guasúre.
Peteĩ kamiõ henyhẽva grafiti-gui oguapýva tape rehe ambue mba'yrumýi ndive
Peteĩ kuimba'e aty ojupi hína esquípe peteĩ pindo hovyũva ári.
Peteĩ kuimba'e henyhẽva líquido-gui peteĩ hidrante ypýpe.
Peteĩ mba'yrumýi oguatáva tape hũre, henyhẽva valija rehe.
Peteî kuimba'e omo'âva hesa kuarahy'âgui motocicleta ári
Peteî kuimba'e omo'âva hesa umi plátano ykére
Peteĩ plato orekóva peteĩ donut chokora ha canela
Mokõi donuts ojejoko yvýre
Peteî tapicha oñapytîva peteî mantel hovy'i ári oñeno ijykére.
Peteĩ mba'yrumýi tavaguasu oguatáva peteĩ tape henyhẽva tavayguágui.
Heta mba'yruguata oguatáva peteĩ tape rehe.
Mokõi mba'yrumýi oguata peteĩ tape rupi peteĩ mbusúpe.
Peteî tapicha ogueraháva peteî mba'yrumýi peteî puente ári.
Peteĩ mbusy ohóva peteĩ parada de autobúsgui.
Peteî kuimba'e ogueraháva peteî kanóa ysyry rembe'ýre
Peteĩ kamiõ henyhẽva marandu'ỹgui oguata peteĩ yvy ojeiko'ỹháme.
Peteĩ mba'yrumýi michĩ ohasa peteĩ óga apoha rendápe.
Umi mba'yrumýi ohóva gasolinera ykére peteĩ cartel tuicháva reheve
Kuña omoinge vino ryru ryepýpe.
Kuñataĩ omosẽvo y ryru peteĩ blender-gui.
Peteĩ mba'e ryakuã oñemboy'u peteĩ kópa morotĩme.
Peteĩ kuimba'e omosarambíva kesu peteĩ mba'e'oka ári.
Peteĩ chef cocina-pe omyenyhẽ so'o heta plato tembi'u ári.
Oî omohendáva tembi'u oñembosako'íva
Peteĩ kamiõ cemento rehegua omombo cemento pyahu tape ári.
Peteî tapicha omyanyhêva torta masa peteî panadápe peteî tembiporu rupive.
Kuña pyahu omyenyhẽva peteĩ víno ryru.
Cerveza oñemboy'u hína peteĩ contenedor henyhẽva hotdog-gui.
Kuña omosarambíva kuimba'épe peteî víno ryru.
Kuña peteĩ tanque gris-pe omyanyhẽ tomate peteĩ batidora-pe.
Kuña oñe'ẽ micrófono-pe oma'ẽ aja vaka rehe.
mokõi surfista oma'ẽvo yvága pytũ ha tormentoso rehe
Peteĩ kuñataĩ omaña itelefóñore.
Peteĩ kuñakarai omaña pe távare peteĩ reloj guasu rapykuéri.
Kuña omaña hína pe espejo-pe ha omopotĩ isy ryguasu.
Peteĩ jagua ijurujáva oma'ẽvo peteĩ kuimba'e Frisbee rehe
Peteî tapicha oma'êva iguýpe umi iñakãrague ha peteî jagua akâ yvate gotyo.
Oĩ ta'anga peteĩ tembi'u rendaguã peteĩva ojoguáva peteĩ ta'anga opytáva
Kuña ojupiva'ekue esquí-pe oma'ẽvo tapykue gotyo
Mitãrusu oma'ẽva peteĩ frigorífico ryepýpe botella rupive.
Peteî kuimba'e ao ao reheve oma'ẽ peteĩ temimbo'e kuñakarai rembiapo rehe.
Mokõive motocicleta oñani peteĩ pista de carrerape peteĩ anuncio de alquiler de Hertz renondépe.
Mokõi jockeye oñorairõ kavaju rehe peteĩ pista-pe.
Mokõi tapicha esquí-pe ojupi yvate gotyo ha oĩ tapicha oma'ẽva.
Peteî kuimba'e oguata peteî moto hûre peteî pista de carrerape.
Mokõi kuimba'e oñorairõva kavaju rehe peteĩ karrétape.
Peteĩ aty motenondehára oñorairõ peteĩ pista-pe.
Peteĩ joqueo oñani hína peteĩ kavaju ári ama guasúpe.
Kuña ijao morotĩva oñorairõ mokõi kuñataĩ ambue rehe esquí-pe.
Peteî aty policía-kuéra oĩva peteĩ desfile renondépe.
Kuimba'ekuéra aty oñembo'ýva ojoykére peteĩ escenario-pe.
Heta tapicha oñembo'y ha peteĩ kuñakarai oñeme'ẽ mokõi hot dog.
Peteĩ aty kuimba'e oñembo'ýva ojuehe ha omboy'u.
Peteĩ kuimba'e peteĩ ñembosaráipe omopyrenda peteĩ balón.
Peteî kuimba'e oityvyro ikorasô tenis kortope.
Peteĩ pelotero oñembosako'íva omombo hag̃ua peteĩ pólvora.
Peteî kuimba'e oitypáva peteĩ béisbol peteĩ árbitro hapykuéri
Heta tapicha ombotyryry kamiõ yvyguýgui tape ári.
Peteî kuimba'e omondéva peteî silla de ruedas tape rehe.
Mokõi vakapipopo mba'apohára oñomoirũva'ekue ojupi hag̃ua vakapipopo rehe.
Peteĩ aty kuimba'e oiporúva yvyra ojejopy hag̃ua skateboard-pe.
Peteî tapicha skateboard ári omosê tapere
Peteî tapicha ombotýva peteï botón televisor-pe.
Kuña ojagarra peteĩ frisbee.
Peteĩ pelotero ojagarra peteĩ pelóta peteĩ pelóta ñembosaráipe.
Peteĩ surfista ojagarra peteĩ ola mar-pe.
Mokõi kuimba'e surf-pe ojagarra peteĩ ola oitypáva.
Kuimba'e ha i-skateboard ojejapiva'ekue oveve jave
Peteĩ ñemuha ohechauka umi paraguasúpe heta kolór.
Peteĩ ta'ãnga omenda ramóva ojehechaukaha cristal kupépe.
Peteĩ obra de arte metal ohechauka peteĩ aravo'i oĩva peteĩ piso mbytépe.
Peteĩ trolley clásico ojehechauka tape mbytépe.
Peteĩ ta'angambyry ohechauka peteĩ vaka peteĩ ka'aguy mbytépe.
Peteĩ tienda hispanoñe'ẽme ohechauka heta mba'e ovetãguio.
Peteî ta'anga umi tapicha oñemonde militar-va ojehechauka tape yképe.
peteĩ sandwiches mbyte oñemoĩva plato ári
Yva ha verdura pyahu ojehechaukáva peteĩ mercado-pe.
Peteĩ karia'y oñembo'ýva peteĩ muro rehe oñe'ẽvo teléfono celular rupive.
Kuimba'e ha kuñakarai oipyhyva'ekue café ha oñomongeta kuñakarai ndive tavaguasúpe oguata aja iky'a rehe
Peteî kuimba'e oñe'ê hína teléfono rupive mesápe okaru jave.
Kuña oguerekóva ikaturã oñemongetáva mokõi tapichápe oguapýva peteĩ banco-pe.
Peteî kuimba'e oñe'êva peteî micrófono-pe traje-pe.
Mokõi pelotero profesional oñomongetáva ñembosaráipe.
Peteî policía kavaju ári oñe'êva peteî policía bicicleta ári.
oĩ tapicha ha peteĩ jirafa omosẽhína iñe'ẽ
Peteĩ tabla de surf hovy, sa'yju ha hovy, osẽva peteĩ ypa'ũ rembe'ýgui.
Peteĩ elefánte omboty hína ikurúpe peteĩ korapýpe.
Heta flecha osẽva peteĩ caja de herramientas naranja-gui.
Peteî mitâkaria'y ijajúra pytäva omboty iñe'ê.
Peteĩ mitã'i omboty hína ijuru ryepýpe peteĩ kuãirũ.
Ta'anga hũ ha morotĩ mokõi py'a ojehecha'ỹva, osẽva mitã rupa ári
