Ndaikatúi ahecha mba'épa he'ise flecha verde.
Kuña oñeno ha ohechauka poapyha cámara-pe
Peteî kuã ohechauka peteî hot dog kesu, salsa ha ketchup reheve.
Peteî cartel henyhêva ha ohechaukava atracción heta hendápe
Heta tapicha oime playa-pe surf tabla reheve ha mokõi kuimba'e he'i y.
Peteî kuimba'e ojoguáva ojoguáva ha oñe'ê jave ohechauka ipo
Heta ta'anga ohechaukáva opa hendápe
Peteî tapicha oipyhyva'ekue peteî control remoto ha oapunta peteî televisor rehe.
Peteĩ wakeboarder ohechauka peteî ola ohasáva y rembe'ýpe
Peteî mano omotenonde control remoto morotî ha morotî peteî pantalla kakuaa gotyo.
Kuña oñe'ẽ jave kuimba'e ndive, ohechaukava'erã yvága gotyo.
Peteî kuimba'e ohechaukáva ipo ambue hendápe, ha'eñoite, upe ta'anga yvatevehápe.
Peteî kuimba'e ohenóiva'ekue ta'angamýipe, ohechaukavo peteî logo iku'arandúpe.
Kuña omopyrenda iñakârague ha'ete peteî pistoleta.
Peteî mitãrusu ohechauka peteî mba'e pe ta'angápe.
Kuña omotenondéva Wii controller cámara gotyo
Peteî kuimba'e ohechaukáva peteî mitâ'i py'ápe.
Kuña ohechauka peteî teléfono peteî caja-pe.
Peteî camarero oapunta peteî cámara ha peteî micrófono peteî tapicha oñe'êva rehe.
Peteî orador profesional escenario-pe ohechaukáva poapy iñirûnguéra ndive
mokôi tapicha omohenda tembi'u peteî mesa ári
Heta tapicha omohenda paraguasúpe y rembe'ýpe.
Peteî mesa oñemohenda pizza tembi'u'arã.
Ojeheja peteî mesa ha upépe oî vino ryru ha peteî tarta.
Oĩ mokõi tembi'u ha peteĩ yva ojejoguáva mesa transparente ári.
Peteî kuimba'e skateboard ári oîva peteî cámara rovái.
Peteĩ cámara oñemoĩva peteĩ mbarakaja okeha renondépe.
Peteĩ ñemenda oñemopyendáva ha peteĩva umi paraguái ovevéva
Mokõi apyka oñemohenda yguasu rembe'ýpe.
Peteî mesa oñemohendava'ekue tembi'u ka'aru ha heta yva, tarta ha pan reheve.
Koty mesa okaruhague oñemohenda tembi'u porãme guarã.
Peteî mesa puku oîháme heta yva, verdura ha pastel.
Peteî tapicha ojepysóva yvytúre skateboard ári kuarahy oike jave.
Heta yryvu guasu oñemoĩ umi kuimbe guasu ykére.
Pe tren eléctrico michî oñembyaty ha ojefotografa.
Peteî kuimba'e ohechauka peteî kuña'ípe peteî tarta guasu hi'arambotýre.
Kavaju ojehechaukaha peteĩ aty'i tapichápe.
Peteî kuimba'e ohechauka kavaju marrõ atyguápe.
Kuña ohechauka ikamby kamera-pe.
Peteî aty tapicha ohechaukáva celular aty guasúpe.
Ta'anga peteî tienda telefónica-pe guarã orekóva peteî kuñakarai ohechaukáva característica.
Kuña oñehekombo'éva mba'éichapa oñembosarái disco golf okaháre.
Peteî karai ombo'éva peteî mitâ'i mba'éichapa ojepya'o.
Peteî televisión ohechaukáva mokõi kuimba'e oheróva sombrero ha peteî kuña.
Irundy ta'anga peteî koty ohechaukáva peteî tupa, ta'anga ha peteî computadora portátil peteî mesa ári.
Kuña ohechaukava'ekue peteî kuimba'épe peteî víno ryru.
Kuña porã ijao hovyũva omboty ijao ohechauka haguã iku'a.
Peteî tapicha oipurúva guante ohechaukáva aravo aravo aravo'ípe
Kuimba'e ha kuña ohechaukava'ekue hi'upyrã.
Mokõi karai guasu oñopytyvõva peteĩ aty guasúpe.
Kuimba'e ha kuñakarai omoma'ẽvo oñondive peteĩ tarta ykére.
A'eramũ 'ga oje'ega monou 'ga upe rakue.
Peteî kuimba'e motocicleta ári ohasáva ambue mba'yrumýi.
Peteî mba'yruguata mokõiha renda pytâ ha morotî ohasa táva mbytépe.
Peteĩ tren pytã peteĩ vía ferroviaria ohasáva peteĩ edificio ykére.
Peteî autobús ohasáva peteî ciclista ha peteî motociclista.
Y ohasa peteĩ puente guýpe, ha upégui ohasa umi mba'yrumýi.
Peteî esquiador ohasáva mokõi tapicha rehe peteî snowmobile-pe.
Peteĩ tren hũ ohasa peteĩ estación-pe.
Peteĩ karai ijedáva ome'ê tembi'u mitãnguérape
Peteî mba'yrumýi osêva tape rehe tata rendy rire
Peteî mba'yrumýi pya'e ohasa peteĩ tape ijykére.
Peteĩ tren pytã ohasa y apére peteĩ puente ári.
Tapichakuéra ojepyso peteî baño orekóva urinal ha baño.
Peteî aty tapicha motocicleta-pe ohasáva umi óga ykére.
Peteî tapicha omohendáva peteî frisbee ipy'a mbytére.
Mitâ'i oñeha'â ojupi kosina kosináme.
Mitâkuña'i oñeha'â ohupyty peteî torta pehêngue.
Peteî jagua osê yvytúre ojagarra haguã peteî frisbee ovevéva.
Oî po osêva ao'i kotýgui ha oñeha'âva ohupyty kuñakarai okeva'ekue.
Mokôi karia'y oipyso ipo ojagarra haguâ peteî disco.
Mitâ'i oipyso ipo oipyhy haĝua peteî manzana pytâ.
Kuña oñesũ ombopu hag̃ua peteĩ balón de tenis peteĩ raqueta reheve.
Peteî karai oipyso ipo ome'ê haĝua peteî mba'e kavaju peguápe.
Peteĩ elefante mitã ohupytýva peteĩ vosa hovy mymba ka'aguy guasúpe.
Oĩ tapicha og̃uahẽva peteĩ ka'aguy rupi ha oiporavo peteĩ.
Peteî po plástico oguahëva peteî mezclador de juguetes plástico.
Peteî kuimba'e oguahëva plato-pe peteî pizza pehêngue.
Peteî tapicha oipyso ipo oipyhy haguã vakapipopo.
Peteî tapicha oñeha'â oguahê control remoto-pe
Tenisero oñenohê raqueta ombopu haguã pelota de tenis
Mitâkuña oñeno ojagarra haguã raqueta de tenis.
Kuña ohekáva pan ha'ãha
Peteî kuimba'e oñesûva peteî mba'e oîva peteî caja-pe
Peteĩ elefante oipyso ijurúpe pe barrera ári.
Peteî kuimba'e oñesûva'ekue peteî rakete rehe ojere haguã peteî pelota de tenis rehe.
Mitâ'i oñeha'â ohupyty peteî frisbee naranja.
Kuña hakã pytã ombotýva oguejy haguã ojagarra haguã raqueta ha pelota de tenis.
Peteî kuimba'e peteî escalera-pe oñeha'âvo ohupyty peteî aranduka
Kuña oipyso ijyva oity mboyve peteî pelota de tenis
Kuña ojupi yvate gotyo rakete reheve oity haguã peteî bala oúvape
Kavaju ho'úva ka'avo ka'aguy rovái peteĩ te'õngue ári.
Aty vakapipopo ñembosarái rehegua
Peteî tapicha oha'âva peteî partido de tenis.
Peteî kuimba'e ombopu violín ikuñáme
Mitã'i oñani vakapipopo reheve.
Mokõi kuña ha irundy kuimba'e oñombohory peteî frisbee morotî rehe
Heta kuimba'e ombopu'ã deporte peteî terreno-pe, oîhápe yvyramáta, muro, peteî autobús ha heta óga ypýpe.
Peteî kuimba'e opytu'u peteî banco yvyrágui ojejapóva.
Jagua iñakã jeko ijára py'ápe
Mokõi tapicha oñani ha opytu'u banco-kuéra ári, ykua ypytũme, ojehechahápe tavaguasu tuichakue
Mokôi mitâ ojapyhy iñakâ ha ogueraha hikuái.
Kuimba'e opytu'u ára pukukue javeve ipy'a ha ipópe hembiporu.
Kuña omopyenda iñakã ijyva akatúa ári
Peteî esquiador opytu'u carrera mbytépe.
Peteî cerveza oñemoî peteî motocicleta ári.
Peteî tapicha ipy yvate ha opytu'u peteî apyka ári peteî mbarakaja hũ ykére.
Tapichakuéra ohasa tenda ojoguáva centro comercial orekóva heta tienda.
Mokôi tapicha oguata tape rehe ombotyva'ekue paraguasúpe.
Kuñanguéra oñomíva oguata tape rupi peteĩ paraguái hovy guýpe.
Peteî karai skateboard-pe oguatáva iky'a.
Mokôi tapicha oguejy koridórpe ha peteî kuimba'e katu okaru peteî oso guasu ykére.
Mokõi tapicha oguata y rembe'ýpe paraguasukuéra reheve.
Peteî karia'y oguerekóva peteî tabla de surf osê pe y apégui.
Mymba hũ oguata ohóvo tapicha aty ypýpe.
Peteî tapicha oguatáva tape karape'íre peteî tape henyhêva gente pyharekue.
Mokõi tapicha oguata jaguápe ne'îrava.
Peteî kuimba'e ha kuña oguatáva peteî mba'yruguata pytâ ha mokôiha rendaguépe.
Peteî kuimba'e ohasáva peteî tren estación-pe.
Kuña omoîva'ekue tomate peteî pizza ári.
Mitâkuña'i omonde peteî sombrero pytâ iñarandúva jagua akâ ári.
Kuña omondeva'ekue ijao oma'ẽvo aravo'íre
Kuñakarai omoakãva omoĩ tembi'u peteĩ plato ári.
Ko kuimba'e omoî monéda peteî parcmetro-pe
Peteî tapicha omoîva so'o peteî tatakuápe peteî espátula rupive.
Mitâkaria'y omoî tembi'u peteî mezcladora-pe
Yvypóra omoĩ decoración yvyra máta ári arete jave.
Peteî kuimba'e omoîva tembi'u peteî plato ári kosináme.
Tapichakuéra omoî tataindy peteî tarta ári ha omoĩ plato ári.
Oime peteî kuimba'e oipurúva peteî corbata.
Peteî kuimba'e ojapóva ojoguávo omoîtaha iky'a peteî tatakua ryepýpe.
Peteî esquiador omoîva esquí nieve-pe peteî óga ypýpe.
Peteî kuimba'e omoîva peteî kuimbe'i peteî microondas-pe.
Peteî kuimba'e omoîva peteî pizza peteî tatakuápe.
Peteî kuimba'e omoîva peteî pavo tatakuápe
Kuña omoîva hi'upyrâ peteî tarta ojejapóva hógape.
Kuña omohendáva pindo ha'eñoháme peteî restaurante-pe.
Peteî portero omoî equipaje peteî cargador-pe tren yképe.
Kuimba'e omyenyhẽ tembi'u ha kuñáva omboy'u vino.
Peteî kuimba'e kotýpe omohendava'ekue peteî paje morotî.
Kuña pyahu snowboard ári, omoĩva guante.
Peteî kuimba'e ojupi peteî apyka guasu pytâ ári peteî kavaju japu ári.
Peteî mbarakaja hũ ojupiva'ekue peteî bañera-pe.
Peteî kuimba'e ojupi peteî pósto de tránsito.
Mitâkuña osêva peteî maleta yvýpe
Mitâkuña ojupi umi jeráfora gotyo ha ha'ekuéra oipyso ijyva ha ojupi hese.
Mitâkaria'y ojupi peteî frigorífico ryepýpe.
Mokôi tapicha ojupi yvyty ári iski ári
Tapichakuéra ojupi yvyty ijyvy'ÿva ykére esquí-pe
Peteî kuimba'e ojupiva'ekue peteî elefante ári ha oñapytîva'ekue ijati'y ári.
Peteî kuimba'e ojupi peteî siloháre itráko henyhêva.
Peteî jagua ojupi peteî tapicha opáyva peteî sóvape.
Peteî jagua omopotî chupe iñakâ peteî kuimba'e.
Peteî mbarakaja oñehetûva'ekue.
Mitâ iñakârague omopotîva'ekue peteî kakuaáva.
Kuña oñeha'ã omopotĩ hag̃ua ijuru peteĩ kesu guasu reheve peteĩ tienda-pe.
Peteî jugador de béisbol oguenohê peteî pelota.
Peteî carpa oñemopu'ãva nieve reheve ha oreko yvyramáta ha esquí hi'aguĩva.
Peteî jugador de béisbol oñani ojagarra haguã peteî pelota ojepoiva'ekue
Kuña omombota'o haguã softball.
Peteî karai iñakârague morotîva tatuado ogueraha ijyvyrata'i y rembe'ýpe.
Mbohapy kuimba'e ogueraháva heta valija tape yképe
Peteĩ kakuaa ogueraháva mitãme ojeiporúva, avei esquí, peteĩ pista de esquí ypýpe.
Peteî jagua hũ oñani hína peteĩ ñu hovy ári.
Kuimba'e ha kuñataî oñani ka'aguýre.
Tenisero oñani ombopu haguã.
Peteî aty militar ohóva peteî autobús escolar gotyo.
Peteî tape ojejapóva cemento yvate ha osyrýva umi vía ferroviaria rehe.
Mokôi tapicha oñani peteî vakapipopo rapykuéri peteî ñu hovyûme.
Kuña oñani peteĩ tape karape ári ha jagua katu peteĩ tabla de ruedas ári.
Heta kuimba'e ha kuña uniforme de fútbol-pe oñani peteĩ campo orekóva heta mesa ha estante.
Peteî surfista oñani ola gotyo playa-pe ijyvyrorenda reheve
Tapichakuéra oguerekóva equipaje ojere ha opukavy.
Peteî mba'yrumýi ojere ijykére peteî accidente vaiete.
Tape guasu mbovymi, sa'yju, ojeíva peteĩ tape tavaguasúpe.
Peteĩ taxi ojere ambue gotyo tape henyhẽva gente rehe.
Peteî mba'yrumýi hovy ha hovy asýva ohóvo tape tavaguasúpe.
Kuña pyahu iporâva omopotîva y tujápe.
Peteî TV ojehecha'ÿva peteî estante yvyrágui ojejapóva.
Peteĩ furgoneta bombero ojere peteĩ esquina-pe.
Peteî kuimba'e oipe'a peteî puesto de bomberos peteî yvyty itágui.
Yvypóra omaña tapykue ha omaña'ỹre ijehe, ojespeja ha'eñoháme.
Ojehecha peteĩ po omoheñóiva peteĩ mezclador morotĩ
Peteî kuimba'e ijao hũva oipe'a peteî tatarendy rokê ha omaña hyepýpe.
Eh, kuimba'e oipe'áva peteî víno ryru.
Kuñakarai oipe'áva computadora portable regádo hóga korapýpe
Peteî tapicha oipe'áva peteî caja de pizza peteî sala de estar-pe.
Peteî elefante oipe'áva ijuru mokõi kuimba'e oma'ê aja.
Peteĩ kosineta michĩ, ojeikehápe ambue koty.
Peteî kuimba'e oipe'áva peteî terminal de incendio omosêva y ro'ysâ peteî calle gotyo.
Peteî kuimba'e oity peteî selfie oipe'ávo computadora pyahu.
Peteî barco michî henyhêva yva rehe río henyhêva barco-kuéra rehe.
Peteĩ ypa'ũ henyhẽva heta ka'avo ha tembi'u renda.
Mesa henyhẽ tembi'u asado-gui
Kuña omyenyhêva kamby ryru.
Koty henyhẽ umi temimbo'e kirirĩháme oikóva.
Mitâkuña'i peteî pirámide y rembe'ýpe omyendyva'ekue tata.
Kuimba'e omyendyva tataindy peteî tarotî ári oguerekóva kuñakarai.
Peteî pelotero ojapóva peteî burbuja peteî chicle rehe.
Kuña oguapýva iñakârague oveve yvytu reheve.
Peteĩ locomotora michĩ omyanyhẽva peteĩ arai yrypy'a.
Peteî kuimba'e omopu'ã peteî bola de plástico
Peteî jagua omokôva peteî kuimba'e.
Peteĩ jockeye omyakã ikavaju ha umi fotógrafo ohai ta'anga.
Mymba aty ojegueraha peteĩ tenda ohasáva tape.
Peteî policía omboty tape ambue tapicha oguatáva motocicleta-pe.
Guardia de color orekóva bandera omyakãva desfile peteî calle-pe.
Kavaju ojejoko ipoguýpe
Heta tapicha oñembo'y ha oma'ê peteî kuimba'e kavaju ári ogueraháva aty kavaju rapykuéri
Heta tapicha oguapýva mesa jerére peteî koty'i oguerekóva computadora portátil, aranduka ha kuatia.
Peteî karia'y desierto-pe oguapýva moto ári
Peteĩ kanóa opytu'u y ári.
Peteî aty aviõ michîva peteĩ tarmac-pe
Peteĩ tren umi vía-pe peteĩ plataforma ykére.
Peteî karai kamisa hovy ári oguapýva peteî apyka ári.
Peteî pizza oñemoîva'ekue salada ykére.
Heta mitã oguapy peteî vy'aguasu aramboty jave
Peteî karai ombotyva'ekue ijapykápe microondas ári.
Peteî kuimba'e ojepyso peteî rakéta tenis rehe
Mitâ'i oñembo'y peteî kosináme pe frigorífico rokê ojepe'a ha mitâ'i ojepyso pe frigorífico ryepýpe.
Paraguái oñembotyva'ekue oñemopyenda óga korapýpe
Mitãkuña'i ipo'a kurusu ha ojepy'apývo peteî mesa ári peteî pizza rectangular ári, calendario mural ha contenedor ykére.
Peteî karai ojepy'amongeta peteî mesa ári, peteî koty hotel-pe.
Peteî kuimba'e oñesû ha oñembosako'i ho'a haguã partido aja.
Peteî tape ñembotypy peteî ángulo-pe ha pe señal de stop ojere.
Peteî kuimba'e ojoguáva ojoguáva ojayvy omyendy haguã tataindy peteî tarógape.
Peteî ta'anga ohapejokóva ojere ijykére peteĩ cruce-pe.
Mitâ'i ojayvy peteî korapýpe ohecha haĝua heta ovecha ra'y.
Mitãkuña oñemonde ao puku rehe oñesũ peteĩ vaka ári ha oreko peteĩ kavaju kapi'i.
Peteĩ jirafa oñesũva peteĩ ka'aguy ñangarekohápe.
Kuña oñesũva'ekue lavabo ári omopotĩvo ijyva peteĩ kesu elektrisado-pe
Peteî tata tricolor oñesû yvy gotyo.
Peteî piloto motociclista peteî pista ojupiva curva-pe.
Peteî kamiõ ohasa tape tren oúvape.
Umi pytagua ohasa peteĩ nivel ohasahápe peteĩ táva henyhẽva gente rehe.
Mokõi mba'yrumýi ha peteî moto peteî tape ohasahápe peteî elefante aty.
Peteî kuimba'e oma'êvo ojuehe, ha'e oreko peteî control remoto ijuru ryepýpe.
Karai omyakã yga'i ysyryguasu gotyo, hetãre.
Kuña peteĩ tabla de surf-pe ojere y apére.
Mokõi pira pire ohóva yguasu rembe'ýpe.
Mokõive surfista oho yguasu gotyo.
Peteî tapicha oguapýva mesa ári ha ohaiva'ekue peteî kuatiáre.
Kuña hyeguasúva ohaiva'ekue isy ryepýpe oguerahahápe peteî oso karape hovy.
Peteî kuimba'e ohaiva'ekue peteî mba'e ha'e oñemongeta jave por teléfono.
Tata rendy tape yképe ojepinta hovy ha morotĩ.
Ojejapo vaka ra'anga ha oñemoha'ãnga rosa ha morotĩ.
Peteî reloj peteî ogaguasu ári orekóva gente pintada ijerére.
Peteî ahoja tata rendy ojepinta peteî bandera estadounidense-icha
Tembipuru'i ogaguasu mbytépe ojepinta jave
Peteî kuimba'e ojupi skimboard playa-pe kuarahy resêpe
Tapichakuéra ojupi peteĩ mba'yrumýi mokõiha rendaguépe, opytáva peteĩ tape henyhẽva mba'epu'apu'a.
Peteî autobús oha'ãrõva peteî tapicha ojupi haguã tape rehe
Peteî kuimba'e ijao hũva ojupi snowboard-pe.
Mitâkuña ojupi mba'yrumýi mbo'ehaópe.
Peteî kuimba'e ojupi peteî ola guasu yguasu ári
Heta mitã skateboard-pe ombojeguáva peteî puente oñemohendáva graffiti-pe
Kuña pyahu omokyre'ÿva mba'yru ku'i oporohapyva'ekue.
Mitâ'i omokô peteî tatakuápe oguerekóva tembi'u
Tesa ha peteî juru ojoguáva ojehecha ko tata rendy ári.
Tata tricolor orekóva diseño peteĩteĩ luz ári.
Peteĩ mba'yru joguaha henyhẽva plátare ha oĩháicha hova.
Mitâkuimba'e ha mitâkuña'i peteî mesa de dibujo de pastel-pe
Peteî kuimba'e ogueraháva peteî frigorífico peteî ógape
Peteî kuimba'e ogueraha peteî tatarendy aña reheve.
Peteî tren plateado osêva tavaguasúpe
Poapy tapicha omomýiva oipytyvõva peteîme ova haguã hógape
Umi camión bombero oguejy tape guasu tavaguasúpe ha umi mitãnguéra oñembosarái.
Peteĩ tren modelo yma guare osẽva vía ári
Mbohapyve tapicha ojupi ysyry rembe'ýpe, mokõi oguejy ha peteĩ ojupi.
Mokõi kuimba'e omomýi yvyra ku'i peteî kamiõ pytã
Peteî panadero omyenyhêva donuts panadero ryepýpe.
Tapichakuéra omba'apo ha oñembyaty peteĩ tenda guasu morotĩ ykére.
Tenis jugador oguata ijykére ha ojagarra raqueta mokõive ipo rehe.
Peteî kuimba'e oitykuáva peteî pelota tenis-pe.
Peteî tapicha ojupi skateboard-pe ha oguahê peteî tramo morotîme.
Mitãrusu oipurúva mita'i ojapi chupe bala.
Peteî kuimba'e oity peteî mba'e ha ojeity chupe peteî yvyra rakâre.
Mokõi kuimba'e ao ao'ípe ombotýva peteĩ gongó martillos-pe.
Peteĩ karréta ogueraháva heta tapicha, ojeity mokõi kavaju rehe.
Peteî kuimba'e omosêva'ekue umi mba'e'oka aeropuerto-pe
Ojehecha peteĩ tren de viajeros opytaha peteĩ muelle-pe.
Peteî mba'yruguata pytâ oñepyrũ opyta tape yképe.
Kuña oguenohẽva tembi'u ombosako'íva tatakuágui
Peteî remolcador pytâ opyta peteî y rembe'ýpe.
Peteĩ tren hovy sa'yju opyta peteĩ estación-pe.
Ygaguasu ogueraháva peteĩ surfista yguasu rembe'ýre.
Pe mba'yrumýi opyta tape yképe.
Peteî barco motor oheja hapykuere ha ogueraha mokôi esquiador yguypegua hapykuéri.
Peteĩ tren opyta peteĩ estación-pe.
Peteî tren ohasa peteî óga ha peteî tape mbytépe.
Peteî kuimba'e oguenohêva peteî pizza peteî tatatîgui.
Peteî kuimba'e omoñe'ê peteî aranduka ha ambue katu ojapyhy peteî jagua.
peteĩ kuñakarai oguapy peteĩ sombríllo guýpe omoñe'ẽvo aranduka
Peteî karai omoñe'ê peteî aranduka peteî mitâme, oîva hupápe.
Mitâkaria'y oñeno hupápe omoñe'êvo kuatiañe'ê ityvýra'ípe.
Kuña omohenda aravo'i heta tapicha oma'ẽ aja.
Ohecháva zoológico-pe ohecha elefante africano
Peteî aty tapicha rembiayhurã oma'êvo yguasu rembe'ýpe.
Oĩ tapicha oma'ẽva ambue tapicha tenis-pe.
Tapichakuéra omaña hína aviõre peteĩ te'õngue rovái.
Peteî karai oguapy aviõme ha omaña TV.
Peteî hot dog oñembyaty peteî película-pe
Kuña pyahu ojejokua toalla playa rayada hovyûme
Kuña oñeno ha ojepyvu toallape, oporojohéi
Peteĩ vagón oñembosako'íva plástico-pe henyhẽva mymba'i ha ambue mba'e.
Peteî mano omyakâva peteî hot dog orekóva ketchup, mostaza ha cebola oñembosaráiva peteî hoja-pe.
Kuñakarai tujami ojahuhápe hi'upyrã
Mitâ'i ojejokua peteî toalle-pe peteî tupa ári.
Peteî tapicha ombojy peteî hilo pytâ peteî ao pehêngue rehe.
Peteî motociclista ojere ha iñirû ojere moto rehe.
Peteĩ ñemuha orekóva dieta bananera ojejoko'ỹva.
Ta'anga aty ogaygua rehegua ombojeguáva peteĩ tataindy ári.
Heta guyra'i hovyũva ojejoko peteĩ óga tuja okápe.
Kuña ojupi jeep marrón rehe
Peteî kuimba'e peteî campo-pe ombyai peteî bate de béisbol.
Ta'anga yma guare peteî kamiõ oñemomombyryva'ekue tape ykére
Mitâkaria'y omyaña peteî tóro peteî martillo'i reheve.
Tata tricolor ho'áva mokõiha peteî korapýpe
Peteî tapicha oîva'ekue yvytúre ho'a jave peteî tabla de surf ha peteî ola guasu.
Peteî jugador de fútbol ho'a yvýpe ha ambue ho'a hi'ári.
Kuña okeva'ekue peteî kuimba'e ykére, mokôive oguapy.
Kuimba'e ho'a ype ola ojopy chupe y rembe'ýgui
Peteî tapicha ojupi peteî tabla de ruedas-pe ha ambue katu ho'a peteî tabla de ruedas-gui.
Peteî tapicha ojupíva skate-pe ho'a haguâ
Peteî tapicha snowboard-pe ho'a nieve ári
Peteî kuimba'e ho'a oñeha'ãvo ojagarra ola surfeando
Peteî tapicha oguerekóva esquí ho'áva peteî pista de esquí henyhêva nieve-gui.
Peteî kuimba'e ho'a ha ikape oveve snowboard-pe.
Mokõi kuimba'e oime esquípe ha peteĩ ho'a.
Aty mba'yrumýi apu'a reheve oguatáva tape pukukue.
Heta tapicha oñembo'y tape mbytépe ha umi motocicleta.
Mitã'i mbo'ehao católico-gua oñemboja'o peteĩ fila-pe, micrófono renondépe.
Hetaiterei mba'yrumýi oñemboja'o joaju.
Mba'yrumýi ojupíva parquímetro rehe tape henyhêva
Umi mba'yrumýi ojupi hikuái tape hũ rehe
Tapichakuéra oñemboja'o peteĩ mba'yrumýi ári peteĩ ára haku jave.
Heta motocicleta oñemboja'o oñemoîvo.
Kuña pyahu ombotýva yvate karóta pyahu.
Peteî kuimba'e ijao'ÿva oguerekóva peteî ku'a pire morotî.
Peteî kuimba'e oñembo'y hesaho'i ha ojagarra peteî Wii Remote.
Mokôi kuimba'e oñangarekóva Wii Remote rehe.
Mitâkaria'y oguapýva yvýpe ha oguerekóva peteî paraguái.
Kuña pire sa'yju, ao ao hu'ũ ha ipópe peteî ku'i'i.
Mitâ'i hovy morotîva oguereko peteî oso karape.
Peteî kuimba'e, omonde peteî sombrero ha oguapy peteî televisor oîva tapére.
Peteî óga itaguigua ituichakue, oguerekóva peteî aravo'i ojoajúva ijyképe.
Karai omoîva casco ojupi ipópe motocicleta
Peteî aravo'i guasu oñemohendáva peteî ogaguasu kupépe
Peteî TV pantalla plana oñemohenda escalera yképe.
Peteî kuimba'e ijao camuflaje ha sombrero hũva ári peteî kavaju ári.
Hetaiterei tapicha omaña peteĩ tenista rehe ombohasa jave peteĩ balón.
Peteî mesa orekóva mokôi torta ha peteî copa de champagne ha mokôi kuñakarai ome'êva torta.
Mokõi tapicha uniforme-pe omoguahëva tembi'u umi invitado-pe.
Hot dog ha patata ojeiporu peteî cartera ojoguáva peteî mba'yrúpe.
Kuña ohekáva balón tenis korapýpe.
Peteî pizza ñana reheguáva ha oñembohysýiva plato-pe
Mbohapy mba'apohára peteî cocina profesional ome'êva tarta.
Kuñanguéra omoguahê tembi'u cafetería-pe plato hovy guýpe.
Aty tapicha oiporúva hot-dog ha patata.
Peteĩ kamiõ hi'upyrã kalamar-kuérape guarã ojopýva ambue kamiõ hi'upyrã.
Peteî tapicha omyendy peteî tataindy oîva peteî tarjeta ári.
Peteî torre reloj kakuaa omyendy peteĩ y rembe'ýpe.
Peteî kuimba'e ao hovy reheve, ohesapéva peteî sigarríllo.
Mokõi tapicha yvyráre, peteĩva ojupi peteĩ ola gotyo ha ambue katu ojupi ambue gotyo.
Peteĩ surfista ojupi peteĩ ola guasu yguasu guasúpe.
Peteî kuimba'e ojupi kavaju ári peteî ka'aguy'i yvyguýpe.
Mokôi tapicha oime peteî motocicleta hũ ári
Kuña ojupi bicicleta ári omaña jave teléfono inteligente rehe
Peteî kuimba'e ojupi y apére peteî tabla de surf ári
Tapichakuéra orekóva kavaju ári peteî elefante guasu.
Kamiõ henyhêva graffiti oiméva tape ykére ambue mba'yrumýi ykére
Peteĩ kuimbaʼe aty ojupi peteĩ sérro hiʼári ha omosẽ iski.
Peteî kuimba'e henyhêva líquido-gui peteî puesto de bombero-pe
Peteî mba'yrumýi henyhêva valija-kuéra oguejýva tape rehe.
Peteî kuimba'e omo'ãvo hesa kuarahy'ãgui motocicleta ári
Peteî kuimba'e omo'ã hesa umi ka'avo rogue ykére
Peteî plato orekóva peteî donut henyhêva chocolate ha peteî donut canela
Peteĩ par de rosquillas henyhẽva relleno-gui
Peteî tapicha oñapytîva peteî sái hovy rehe ha oñeno ijykére.
Peteî mba'yrumýi tavaguasúpe ohasáva tape henyhêva gente hetaitéva tavaguasúpe.
Peteî aty mbosako'ihára oguatáva tape pukukue javeve umi mba'yrumýi reheve.
Mokõi mba'yrumýi ojupi peteĩ tape rehe peteĩ mba'yrumýi hovy yképe.
Peteî tapicha omomýiva peteî mba'yrumýi peteî puente gotyo.
Peteî mba'yrumýi osê ohóvo peteî mba'yrumýi rendagui.
Peteî kuimba'e omotenondéva peteî barco río rembe'ýre
Peteî kamiõ henyhêva marandu'asâihágui ohasa peteî yvy ojeiko'ỹháme.
Peteî mba'yrumýi michî ha ipya'éva ohasa peteî tienda de muebles rovái.
Umi mba'yrumýi ohasa estación de servicio ykére orekóva peteî cartel kakuaa
Kuña omoinge vino ryru ryepýpe.
Mitâkuña omyanyhêva peteî mba'e'okaru mixingógui.
Peteĩ mba'e ryakuã omyenyhẽva peteĩ kópa morotĩme.
Peteî kuimba'e omyenyhêva kesu peteî balanza alimenticia ári.
Peteĩ chef omyenyhẽ so'o heta plato tembi'u ári.
Oî omohendáva tembi'u oje'úva
Peteî kamiõ cemento rehegua omombo cemento pyahu tape rehe.
Peteî tapicha omyanyhêva peteî pastel-pegua masa peteî asado-pe.
Kuña pyahu omyenyhẽva vino ryru.
Cerveza omohendáva peteî contenedor henyhêva hot-dogs.
Kuña omosarambíva kuimba'épe peteî víno ryru.
Kuña ijao hovy morotĩva omoinge tomate peteî mezcladora-pe.
Kuña oñe'êkuri michîmi, oma'êvo vaka rehe.
Mokôi surfista omaña yvága rehe ha'etéva pytû ha yvytu atã
Peteĩ kuñataĩ omaña imóvil rehe.
Kuñakarai omaña táva rehe peteĩ aravo'i guasu rapykuéri.
Kuña omaña espéhope ha omopotĩ isy ry'aikue.
Peteî jagua oipyso iñe'ê omañavo peteî frisbee peteî kuimba'e ykére
Peteî tapicha oma'êvo umi sapatu oguerekóva peteî jagua akâ ári.
Ko'ã señal peteî tenda restauración orekóva peteî ojoguáva señal de alto
Kuña ojupi esquípe omaña tapicha ohasávare
Mitãrusu oma'ẽva peteî frigorífico ryepýpe, botella rupive.
Peteî kuimba'e ao hekópe omaña mba'épa peteî temimbo'e proyecto.
Mokõive motocicleta oñani peteî anuncio de alquiler hertz rovái.
Mokõi jockeye omboguata kavaju peteĩ pista-pe.
Mokôi tapicha esquípe oñani peteî pindo ári ha oî tapicha oma'êva.
Peteî kuimba'e peteî moto de carrera hũva reheve peteî pista de carreras jerére.
Mokõi kuimba'e oñani kavaju rehe peteĩ karrétape.
Peteî motenondehára aty oiko peteî carrera peteî pista-pe.
Peteĩ jockeye oñani kavaju ári ama guasúpe.
Kuña ao morotîme oñorairô mokõi kuñataî ambue kuñakarai ndive.
Aty policial-kuéra oñembo'ýva peteî desfile renondépe
Kuimba'ekuéra aty oñembo'y ojoykére peteĩ escenario-pe.
Heta tapicha oñemboja ha peteî kuñakarai oñeme'êkuri chupe mokôi hot-dog.
Peteî aty kuimba'e omboy'u haĝua, ojoykére.
Peteî kuimba'e peteî ñúme oitykuáva peteî bate peteî pelotape.
Peteî kuimba'e oitypa raqueta tenis korapýpe.
Peteĩ pelotero oñembosakoʼi oity hag̃ua peteĩ pelóta ojepoi vaʼekuépe.
Peteî kuimba'e oitypáva peteî pelota peteî árbitro hapykuéri
Heta tapicha omosẽ kamiõ tape po'ígui ha oity tape ári.
Peteî kuimba'e omosêva peteî silla de ruedas calle-pe.
Mokõi vakapipopo mba'apohára oñorairõ hikuái.
Peteî aty kuimba'e oiporúva yvyra'i ojehupi haĝua hikuái yvyráre.
Peteî tapicha peteî tabla de ruedas-pe ojepytaso tape yképe
Peteî tapicha ombotývo peteï botón peteî televisor-pe.
Kuña omopu'ã ipo ojagarra haguã Frisbee.
Peteî pelotéro ojagarra peteî pelota peteï campo de béisbol-pe.
Peteĩ surfista ojagarra peteĩ ola mar-pe.
Mokõi kuimba'e ojupi y rembe'ýpe ha ojagarra peteĩ ola oúva.
Kuimba'e ha itapỹi ojagarra ovevévo
Peteĩ tienda-pe ojehecha paraguasukuéra opáichagua color-pe peteĩ muro-pe.
Ta'anga peteî pareja omendáva ramóva ojehechauka peteî ventana kupépe
Peteĩ ta'ãnga'i metalguigua ohechauka peteĩ aravo'i yvýpe.
Peteĩ tranvía clásico ojehecha tape mbytépe.
Peteĩ pantalla de televisión ohechaukáva peteĩ vaka ka'aguy mbytépe.
Peteî vitrina español-pe ohechauka hetaiterei mba'e oúva ovetãgui.
Peteî ta'anga umi gente oñemonde militar-va ojehecha tape rehe.
Peteĩ ta'anga sandwiches-kuéra mbyteguigua oñembojeguáva plato yvate ári
Yva ha verdúra ojehechahápe peteĩ márkope
Mitãrusu oñe'ẽva teléfono celular rupive, pared rovái.
Kuimba'e ha kuñakarai oñomongetáva peteî kuñakarai ndive okápe, oguata aja hikuái jaguakuéra ndive
Peteî karai oñe'ê teléfono rupive peteî karu guasu aja.
Peteî kuñakarai jagua ndive oñemongeta mokõi tapicha oguapýva peteî banco ári.
Peteî kuimba'e ao ha oñe'êva peteî micrófono-pe.
Mokõi pelotero oñemongeta hína pe estadio-pe.
Peteî policía kavaju ári oñe'êva peteî policía motocicleta ári ndive.
Oime avei heta hénte ha peteĩ jirafa oipyso lája
Peteĩ tabla de surf hovy, sa'yju ha hovy, oñemitỹ yvyku'i rembe'ýpe.
Peteĩ elefante omosẽ peteĩ horno-pe peteĩ mba'e'oka rupive.
Heta flecha ohasáva peteî caja de herramientas naranja.
Mitâkaria'y oguerekóva peteî nóta de mariposa oipyso iñe'ê.
Mitâ'i oipy'ajoko peteî ku'i'i.
Ta'anga hũ ha morotĩ mokõi mitã'i py'a nandi osẽva tupa'ígui.
